---

language: python
cache: pip

matrix:
  include:
    - name: "Ansible latest on Bionic"
      dist: bionic
      before_install:
        - sudo apt-add-repository ppa:ansible/ansible -y
        - sudo apt-get update -q
        - sudo apt-get install ansible -y
      install:
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint

script:
  - ansible --version
  - ansible-lint --version
  - ansible-galaxy --version
  - ansible-lint -v .
  - ansible-playbook -i tests/inventory --syntax-check tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
