---

language: python
cache: pip

matrix:
  include:
    - name: "Ansible 2.2.3.0 on Trusty"
      python: 2.7
      dist: trusty
      sudo: true
      install:
        - pip install -U ansible==2.2.3.0
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip install ansible-lint
        - pip install ansible-review
    - name: "Ansible 2.3.3.0 on Trusty"
      python: 2.7
      dist: trusty
      sudo: true
      install:
        - pip install -U ansible==2.3.3.0
        - sudo ansible-galaxy install --force -r tests/requirements.yml
        - pip install ansible-lint
        - pip install ansible-review
    - name: "Ansible 2.3.3.0 on Trusty"
      python: 2.7
      dist: trusty
      sudo: true
      install:
        - pip install -U ansible==2.3.3.0
        - sudo ansible-galaxy install --force -r tests/requirements.yml
        - pip install ansible-lint
        - pip install ansible-review
    - name: "Ansible 2.4.6.0 on Trusty"
      python: 2.7
      dist: trusty
      sudo: true
      install:
        - pip install -U ansible==2.4.6.0
        - sudo ansible-galaxy install --force -r tests/requirements.yml
        - pip install ansible-lint
        - pip install ansible-review
    - name: "Ansible PPA 2.5.0 on Precise"
      python: 2.7
      dist: precise
      addons:
        apt:
          sources:
            - ppa:ansible/ansible
          packages:
            - ansible
      install:
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip install ansible-lint
        - pip install ansible-review
    - name: "Ansible 2.5.15 on Xenial"
      python: 3.6
      dist: xenial
      install:
        - pip3 install -U ansible==2.5.15
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review
    - name: "Ansible 2.6.19 on Xenial"
      python: 3.6
      dist: xenial
      install:
        - pip3 install -U ansible==2.6.19
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review
    - name: "Ansible 2.7.13 on Xenial"
      python: 3.6
      dist: xenial
      install:
        - pip3 install -U ansible==2.7.13
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review
    - name: "Ansible PPA 2.8.5 on Trusty"
      python: 2.7
      dist: trusty
      addons:
        apt:
          sources:
            - ppa:ansible/ansible
          packages:
            - ansible=2.8.5
      install:
        - pip3 install -U ansible==2.8.5
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review
    - name: "Ansible 2.8.5 on Xenial"
      python: 3.6
      dist: xenial
      install:
        - pip3 install -U ansible==2.8.5
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review
    - name: "Ansible latest on Bionic"
      python: 3.7
      dist: bionic
      install:
        - pip3 install -U ansible
        - ansible-galaxy install --force -r tests/requirements.yml
        - pip3 install ansible-lint
        - pip3 install ansible-review

script:
  - ansible --version
  - ansible-lint --version
  - ansible-review --version
  - ansible-galaxy --version
  - ansible-lint -v .
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q
  - ansible-playbook -i tests/inventory --syntax-check tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
